#define GL_RESET_BUTTON_IS_PRESS        0
#define GL_WPS_BUTTON_IS_PRESS          0
#define GL_SCREEN_BUTTON_IS_PRESS       0

#if defined(CONFIG_TARGET_IPQ6018_JDCLOUD_RE_CS_02) || \
    defined(CONFIG_TARGET_IPQ6018_JDCLOUD_RE_SS_01) || \
    defined(CONFIG_TARGET_IPQ6018_LINK_NN6000_V1) || \
    defined(CONFIG_TARGET_IPQ6018_LINK_NN6000_V2)
#define HAS_WPS_KEY 1
#endif

#ifdef CONFIG_TARGET_IPQ6018_JDCLOUD_RE_CS_02
#define HAS_SCREEN_KEY 1
#endif

#define LED_ON 1
#define LED_OFF 0

#define WEBFAILSAFE_PROGRESS_START		0
#define WEBFAILSAFE_PROGRESS_TIMEOUT		1
#define WEBFAILSAFE_PROGRESS_UPLOAD_READY	2
#define WEBFAILSAFE_PROGRESS_UPGRADE_READY	3
#define WEBFAILSAFE_PROGRESS_UPGRADE_FAILED	4

enum {
    WEBFAILSAFE_UPGRADE_TYPE_FIRMWARE,
    WEBFAILSAFE_UPGRADE_TYPE_UBOOT,
    WEBFAILSAFE_UPGRADE_TYPE_ART,
    WEBFAILSAFE_UPGRADE_TYPE_IMG,
    WEBFAILSAFE_UPGRADE_TYPE_CDT,
    WEBFAILSAFE_UPGRADE_TYPE_UIMAGE,
};

#define CONFIG_LOADADDR                                 0x44000000
#define WEBFAILSAFE_UPLOAD_RAM_ADDRESS                  0x50000000

#define WEBFAILSAFE_UPLOAD_PADDING_SIZE_IN_BYTES        (1024*1024)
#define WEBFAILSAFE_UPLOAD_UBOOT_SIZE_IN_BYTES          (640*1024)
#define WEBFAILSAFE_UPLOAD_ART_SIZE_IN_BYTES            (256*1024)
#define WEBFAILSAFE_UPLOAD_ART_BIG_SIZE_IN_BYTES        (512*1024)
#define WEBFAILSAFE_UPLOAD_CDT_SIZE_IN_BYTES            (256*1024)

#define HEADER_MAGIC_CDT         0x00544443
#define HEADER_MAGIC_ELF         0x464C457F
#define HEADER_MAGIC_EMMC        0xAA55
#define HEADER_MAGIC_FIT         0xEDFE0DD0
#define HEADER_MAGIC_JDCLOUD     0x73616C46
#define HEADER_MAGIC_SQUASHFS    0x73717368
#define HEADER_MAGIC_SYSUPGRADE1 0x75737973
#define HEADER_MAGIC_SYSUPGRADE2 0x61726770
#define HEADER_MAGIC_UBI         0x23494255

enum {
    FW_TYPE_UNKNOWN = -1,
    FW_TYPE_CDT,
    FW_TYPE_ELF,
    FW_TYPE_EMMC,
    FW_TYPE_FACTORY_KERNEL6M,
    FW_TYPE_FACTORY_KERNEL12M,
    FW_TYPE_FIT,
    FW_TYPE_JDCLOUD,
    FW_TYPE_SYSUPGRADE,
    FW_TYPE_UBI,
};

int auto_update_by_tftp(void);
int check_fw_type(void *address);
void print_fw_type(int fw_type);
void led_toggle(const char *gpio_name);
void led_on(const char *gpio_name);
void led_off(const char *gpio_name);
void check_button_is_press(void);
